# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  HOA_Stage_Version_V1_Versions:
    docker:
      - image: circleci/golang
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install rtapi
          command: |
            go get github.com/nginxinc/rtapi
      - run:
          name: Update configuration
          command: |
            cat ./configurations/hoa/version_v1_versions.json
      - run:
          name: Executing rtapi
          command: |
            rtapi --file ./configurations/hoa/version_v1_versions.json --output hoa_version_v1_versions_report.pdf
      - store_artifacts:
          path: ~/repo/hoa_version_v1_versions_report.pdf

workflows:
  version: 2
  hoa-stage:
    jobs:
      - Approve_HOA_Stage_Version_V1_Versions:
          type: approval
          filters:
            branches:
              only: hoa_stage
      - HOA_Stage_Version_V1_Versions:
          requires:
            - Approve_HOA_Stage_Version_V1_Versions
          filters:
            branches:
              only: hoa_stage
