# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  HOAStageVersionV1Versions:
    docker: circleci/go
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install rtapi
          command: |
            go get github.com/nginxinc/rtapi
      - run:
          name: Update configuration
          command: |
            sed -i s/###BACKEND_DOMAIN###/${US_BFF_DOMAIN_STAGE}/g ./configurations/hoa/version_v1_versions.json
            sed -i s/###JWT_TOKEN###/${JWT_TOKEN}/g ./configurations/hoa/version_v1_versions.json
            sed -i s/###IFM_SID###/${SID_HOA}/g ./configurations/hoa/version_v1_versions.json
            cat ./configurations/hoa/version_v1_versions.json
      - run:
          name: Executing rtapi
          command: |
            rtapi --file ../configurations/hoa/version_v1_versions.json --output hoa_version_v1_versions_report.pdf
      - store_artifacts:
          path: ~/repo/hoa_version_v1_versions_report.pdf

workflows:
  version: 2
  hoa-stage:
    jobs:
      - ApproveHOAStageVersionV1Versions:
          type: approval
          filters:
            branches:
              only: hoa_stage
      - HOAStageVersionV1Versions:
          requires:
            - ApproveHOAStageVersionV1Versions
          filters:
            branches:
              only: hoa_stage
